// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Boss - standing still":return img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . 5 . . 
. 2 . . f 2 2 2 2 2 2 f . . . . 
. 5 . f 5 2 2 2 2 2 2 2 5 . . . 
. . . f 2 2 f f f f 5 2 f . . . 
. . . f 2 f 2 f f 2 f 4 f . . . 
. . f 4 2 f 5 f f 5 f 2 2 f . . 
. . f 2 c f f f f f f 2 4 f . . 
. f 4 2 c f f 2 2 f f c 4 f . . 
. f 4 2 2 c c 2 2 c c 2 2 2 5 . 
. . 5 f 2 2 2 f f 4 2 2 5 f . . 
. . c c 2 4 2 f f 2 2 4 2 f . . 
. . . . 4 4 f f f f 4 5 . . . . 
. . . . 5 c f f 2 f f 5 . . . 2 
. . . . . c f c c f 2 . . . . . 
. . . . . c 2 . . c f . . . . . 
`;
            case "image2":
            case "Boss -  side":return img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
